0.0.1

diff --git a/jssh b/jssh
--- a/jssh
+++ b/jssh
@@ -5,9 +5,23 @@
 # or one of jssh's native options.
 ###############################################################
 
+name="jssh"
+version="0.0.2"
+author="Md. Jahidul Hamid"
+source="https://github.com/neurobin/jssh"
+bugt="$source/issues"
+
+verinfo="
+Name:       $name
+Version:    $version
+Author:     $author
+Source:     $source
+Bug report: $bugt
+"
+
 help="
 ########################################################
-######################### `basename "$0"` #########################
+######################### $name #########################
 # Convenience wrapper for ssh
 # ######################################################
 #
@@ -17,9 +31,75 @@ help="
 # 
 # -cdw : run cd WorkDir after logging in
 # -c   : create config file
+# -cl  : create config file link to existing config
 ########################################################
 "
+configh="
+############################# jssh config file ################################
+# Property names are case insensitive
+# if path doesn't have / at the beginning
+# it will be taken relative to /home/user (~)
+# '#' doesn't mean a comment. Everything not in the format: 
+# Property=value are comments.
+# You don't need to delete anything inside this block.
+# You can comment out a line safely with a '#' at start, even though it
+# has no special meaning in this config file.
+###############################################################################
+"
 export logdir="$HOME/.neurobin/jssh"
+
+printEndHelp(){
+#takes the configfile name (without .conf) as 1st argument
+#and path as 2nd argument
+echo "
+    Saved as: $2
+    You will call jssh for this configuration like this:
+    jssh $1 other_ssh_options_or_args
+    'jssh $1' is the native jssh part. All other arguments
+    will be forwarded to ssh command. Any jssh native option
+    must be passed before $1.
+    You can edit the config file to make further changes.
+    "
+
+}
+
+createConfigFileLink(){
+    while true;do
+        echo "Enter existing config file name (without .conf): "
+        read conf
+        if [ x"$conf" != x ];then
+            configfile="$logdir/${conf}.conf"
+            if [ -f "$configfile" ];then
+                break
+            else
+                echo "Config file: $configfile doesn't exist"
+            fi
+        fi
+    done
+    echo "
+    Give an easy and memorable name to your config file, something like example.com.
+    Later you will call jssh with this name to login to remote.
+    "
+    while true;do
+        echo "Enter config file (link) name (without .conf): "
+        read conf
+        if [ x"$conf" != x ];then
+            configfile_l="$logdir/${conf}.conf"
+            if [ -f "$configfile_l" ];then
+                while true;do
+                    echo "Overwrite (y/n)?: "
+                    read yn
+                    if [ x"$yn" = xy ] || [ x"$yn" = xY ] || [ x"$yn" = xn ] || [ x"$yn" = xN ];then
+                        break
+                    fi
+                done
+            fi
+            ln -sf "$configfile" "$configfile_l" &&
+            printEndHelp "$conf" "$configfile_l"
+            break
+        fi
+    done
+}
 
 createConfigFile(){
     echo "
@@ -27,7 +107,7 @@ createConfigFile(){
     Later you will call jssh with this name to login to remote.
     "
     while true;do
-        echo "Enter config file name: "
+        echo "Enter config file name (without .conf): "
         read conf
         if [ x"$conf" != x ];then
             break
@@ -43,18 +123,8 @@ createConfigFile(){
             fi
         done
     fi
-    
-    echo "
-############################# jssh config file ################################
-# Property names are case insensitive
-# if path doesn't have / at the beginning
-# it will be taken relative to /home/user (~)
-# '#' doesn't mean a comment. Everything not in the format: 
-# Property=value are comments.
-# You don't need to delete anything inside this block.
-# You can comment out a line safely with a '#' at start, even though it
-# has no special meaning in this config file.
-###############################################################################" > "$configfile"
+    #put config heding to config file
+    echo "$configh" > "$configfile"
     while true;do
         echo "Enter domain/IP: "
         read d1
@@ -90,15 +160,7 @@ createConfigFile(){
     else
         echo "Not specifying working directory for now."
     fi
-    echo "
-    config file saved as: $configfile
-    You will call jssh for this configuration like this:
-    jssh $conf other_ssh_options_or_args
-    'jssh $conf' is the native jssh part. All other arguments
-    will be forwarded to ssh command. Any jssh native option
-    must be passed before $conf.
-    You can edit the config file to make further changes.
-    "
+    printEndHelp "$conf" "$configfile"
 }
 
 
@@ -108,25 +170,62 @@ if [ "x$1" = "x" ];then
   exit 1
 fi
 cdw=false
-# $1 can also be --cd-doc-root or -cdw which will run cd WorkDir before running any other command
-if [ "x$1" = "x--cd-doc-root" ] || [ "x$1" = "x-cdw" ];then
-  shift
-  cdw=true
+
+case "$1" in
+    -h | --help )
+        echo "$help"
+        shift
+        exit 0
+        ;;
+    -v | --version )
+        echo "$verinfo"
+        shift
+        exit 0
+        ;;
+    --cd-work-dir | -cdw )
+        cdw=true
+        shift
+        ;;
+    --create-config | -c )
+        createConfigFile
+        shift
+        exit 0
+        ;;
+    --create-config-link | -cl )
+        createConfigFileLink
+        shift
+        exit 0
+        ;;
+    -* )
+        echo "E: Invalid native jssh option: $1. Abort."
+        shift
+        exit 1
+        ;;
+    * )
+        dom="$1"
+        shift
+        ;;
+esac
+
+#dom may not be found at the beginning. We will try once more if not found
+
+if [ x"$dom" = x ];then
+    if [ x"$1" != x ];then
+        dom="$1"
+        shift
+    else
+        echo "E: config file or domain name required. Abort."
+        exit 1
+    fi
 fi
 
-if [ "x$1" = "x--create-config" ] || [ "x$1" = "x-c" ];then
-  shift
-  createConfigFile
-  exit 0
-fi
-
-dom="$1"
 configfile="$logdir/${dom}.conf"
-#configfile is not empty, the following command is safe.
+
 if [ ! -f "$configfile" ];then 
-  echo "E: Configuration file doesn't exist for $dom: Couldn't find $configfile "
+  echo "E: Configuration file doesn't exist for $dom: Couldn't find $configfile . Abort."
   exit 1
 fi
+
 host=`grep -sio '\([[:blank:]]*\|^\)Host[[:blank:]]*=[[:blank:]]*[^[:blank:]]*' "$configfile"`
 host=`echo "$host" |grep -sio '[^=]*$' |head -1`
 port=`grep -sio '\([[:blank:]]*\|^\)Port=.*' "$configfile"`
@@ -137,24 +236,23 @@ droot="`grep -sio '\([[:blank:]]*\|^\)WorkDir=.*' "$configfile"`"
 droot="`echo "$droot" |grep -sio '[^=]*$' |head -1`"
 
 if [ "x$host" = "x" ]; then host="$dom"; fi
-if [ "x$port" = "x" ]; then echo "Port required";exit 1; fi
-if [ "x$user" = "x" ]; then echo "username required";exit 1; fi
-if [ "x$droot" = "x" ] && $cdw; then echo "WorkDir required";exit 1; fi
+if [ "x$port" = "x" ]; then echo "E: Port required. Abort.";exit 1; fi
+if [ "x$user" = "x" ]; then echo "E: username required. Abort.";exit 1; fi
+if [ "x$droot" = "x" ] && $cdw; then echo "E: WorkDir required. Abort.";exit 1; fi
 
 #echo "$host"
 #echo "$port"
 #echo "$user"
 #echo "$droot"
 
-shift
-
 if $cdw;then
-  com="cd $droot
-   ${1+"$@"}"
-  ssh -p "$port" "$user@$host" "$com"
+    com=${1+"$@"}
+    com="cd $droot
+    $com"
+    ssh -p "$port" "$user@$host" "$com"
 else
-  ssh -p "$port" "$user@$host" "${1+"$@"}"
+    ssh -p "$port" "$user@$host" ${1+"$@"}
 fi
 if [ ! $? -eq 0 ];then
-  echo "help"
+    echo "$help"
 fi
